# Generated by Django 3.0.3 on 2020-02-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician1',
            fields=[
                ('Artist', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=100)),
                ('charges', models.IntegerField()),
                ('contact', models.IntegerField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
